export const Menucontent = [
    ['people-places-time','People, Places & Time','What is an Indian tribe or nation and why are there tribes today?','"Tribes," in the past and today, are groups of Indians recognized by the United States as sovereign entities, that is, nations within a nation.'],
    ['homeland-use','The Homeland & its Use','What relevance do fishing, ricing, and forestry have for Indian people today?','These activities provide subsistence and commercial opportunities, and also are an expression of cultural identity.'],
    ['marketplace','The Marketplace','What roles have Indian people played in the regional economy?','They were instrumental in the success of the fur trade, played a key role in regional trade in the 18th and 19th centuries, were essential to the tourist trade and commerce in the 20th century, and today own businesses that employ hundreds of people locally.'],
    ['treaties','Treaties','What are treaty rights and why are they relevant today?','A treaty is a contract between two sovereign nations. Treaty rights are the foundation of U. S. law on Indian rights.'],
    ['identities','Identities','What is Indian identity and how is it legally established?','Cultural identity follows from participation in an Indian community, but legal identity is established by meeting certain federal criteria or enrollment criteria of a particular tribe.'],
    ['property','Property','Why did Indian people petition Congress to return objects in museums to tribes?','Indians insist that they have the right to control the disposition of the remains of their ancestors and religious and other objects that have been removed from their homeland.'],
    ['indian-imagery','Indian Imagery','What imagery is associated with Indians and why does it matter?','Stereotypical "Indian" imagery has consistently been used in the United States and this imagery has been harmful to Native people in export constious ways, including psychologically, economically, and politically.'],
    ['are-midwest-indians-typical','Are Midwest Indians Typical?']
];
